version: "3"

services:
    php:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./php:/var/www/html/
            - ./apache/log/:/var/log/apache2/
            - ./config/php.ini:/usr/local/etc/php/php.ini
        links:
            - mysql
        networks:
            - default

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./config/my.cnf:/etc/mysql/my.cnf
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql
        ports:
            - 81:80
        environment:
            PMA_ABSOLUTE_URI: http://domain/phpmyadmin/
            PMA_HOST: mysql
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ROOT_PASSWORD: app